version: '3.9'

services:
  backend:
    build: backend/
    ports:
      - "6500:6500"
    restart: always
    environment:
      - MONGO_URI=mongodb+srv://ahkcht981:Ahkcht98@bstorec.5l8i8lk.mongodb.net/nicerDebt

  frontend:
    build: frontend/vls/
    ports:
      - "3000:3000"
    restart: always
